version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: paceit_postgres
    environment:
      POSTGRES_USER: paceit_user
      POSTGRES_PASSWORD: paceit_password
      POSTGRES_DB: paceit_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - paceit_network

volumes:
  postgres_data:

networks:
  paceit_network:
    driver: bridge
